kind: pipeline
type: docker
name: hello-world

steps:
- name: en
  image: alpine
  commands:
  - echo "hello world!"

- name: fr
  image: alpine
  commands:
  - echo "bonjour monde!"

- name: sp
  image: alpine
  commands:
  - echo "hola mundo!"

- name: notify
  image: plugins/slack
  settings:
    channel: ops
    webhook:
      from_secret: SLACK_URL
