version: '3'
services:
  gunicorn:
    env_file:
      - .env
    image: xmrauctions:latest
    command: [".venv/bin/gunicorn", "-b", "0.0.0.0:8000", "xmrauctions.wsgi"]
    ports:
      - 8000:8000
    depends_on:
      - "db"
  huey:
    env_file:
      - .env
    image: xmrauctions:latest
    command: ["./manage.py", "run_huey", "-q"]
    depends_on:
      - "db"
