global:
  scrape_interval: 10s
  evaluation_interval: 60s

  external_labels:
    monitor: django-monitor

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]
  - job_name: "django"
    static_configs:
    - targets: ["gunicorn:8000"]

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

rule_files:
- "django_rules.yml"
