version: '3'
services:
  db:
    image: postgres:9.6.15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  cache:
    image: redis:5.0.7-buster
    ports:
      - 6379:6379
  
