version: '3'
services:
  gunicorn:
    env_file:
      - .env
    image: xmrauctions:latest
    command: [".venv/bin/gunicorn", "-b", "0.0.0.0:8000", "xmrauctions.wsgi"]
    ports:
      - 8000:8000
    depends_on:
      - "db"
  huey:
    env_file:
      - .env
    image: xmrauctions:latest
    command: ["./manage.py", "run_huey", "-q"]
    depends_on:
      - "db"
  grafana:
    image: grafana/grafana:6.5.0
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      HOSTNAME: grafana
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_ANALYTICS_CHECK_FOR_UPDATES: "false"
    volumes:
      - ./Docker/files/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/default.yaml:ro
      - ./Docker/files/grafana/prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml:ro
      - ./Docker/files/grafana/xmrauctions_metrics.json:/var/lib/grafana/dashboards/xmrauctions_metrics.json:ro
      - grafana:/var/lib/grafana
  prometheus:
    image: prom/prometheus:v2.15.2
    ports:
      - 9090:9090
    volumes:
      - ./Docker/files/prometheus:/etc/prometheus
      - prometheus:/prometheus

volumes:
  grafana:
  prometheus:
